; Custom copy for the Aether NSIS installer (English).
LangString addOrReinstall ${LANG_ENGLISH} "Add/Reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already Installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Select the operation you want to perform and click Next to continue."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is already running. Close it, then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is running.$\nClick OK to close it and continue."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose the maintenance option to perform."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Do not uninstall"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Do not uninstall (downgrading without uninstall is disabled for this installer)"
LangString failedToKillApp ${LANG_ENGLISH} "Could not close {{product_name}}. Close it yourself, then try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed. Installing an older version is not recommended. If you still want to continue, uninstall the current version first."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is already installed. Uninstalling it first is recommended."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for this installer. Use the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 failed to install. Aether needs it to run. Restart the installer and try again."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: downloading WebView2 failed — $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: WebView2 install failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete Aether library data"
